name: "Deploy site"

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
  workflow_dispatch:
    # Allow manually running workflow
  # no scheduled deploy neccessary for now
  # but maybe in the future if I add calendar support this way
  # schedule:
  #   - cron: '23 2 * * *'

env:
  DEPLOY: >-
    ${{
    github.event_name != 'pull_request'
    &&
    github.ref == 'refs/heads/main'
    }}
  OUTPUT: _html

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
      
      - name: Install Lektor
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install lektor

      - name: Build lektor website
        run: lektor build -O '${{ env.OUTPUT }}'

      -   name: Setup SSH Keys and known_hosts
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"

      - name: Deploy lektor website
        if: env.DEPLOY == 'true'
        run: lektor deploy -O '${{ env.OUTPUT }}' github
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
